// chrome.downloads lets an extension start a download, watch it and search the
// browser's download history. The "downloads" permission covers all of it.

const status = document.getElementById("status");
const list = document.getElementById("list");

// The file is built here rather than fetched, so the example needs no host
// permission and works offline. A blob: URL would be revoked before the
// download finished, so a data: URL is used instead.
document.getElementById("download").addEventListener("click", () => {
  const text = `Generated by the Downloads example\n${new Date().toISOString()}\n`;
  const url = `data:text/plain;charset=utf-8,${encodeURIComponent(text)}`;

  chrome.downloads.download(
    {
      url,
      filename: "web-extensions-samples/example.txt", // Relative to the Downloads folder.
      saveAs: false,
      conflictAction: "uniquify", // Never silently overwrite an existing file.
    },
    (downloadId) => {
      if (chrome.runtime.lastError) {
        status.textContent = chrome.runtime.lastError.message;
        return;
      }
      status.textContent = `Download #${downloadId} started.`;
      refresh();
    }
  );
});

// onChanged reports every state transition of any download, so progress can be
// followed without polling.
chrome.downloads.onChanged.addListener((delta) => {
  if (delta.state) {
    status.textContent = `Download #${delta.id} is now ${delta.state.current}.`;
    refresh();
  }
});

// search() with an empty query returns everything; orderBy/limit narrow it.
function refresh() {
  chrome.downloads.search({ limit: 5, orderBy: ["-startTime"] }, (items) => {
    list.replaceChildren();

    if (items.length === 0) {
      list.textContent = "No downloads yet.";
      return;
    }

    for (const item of items) {
      const entry = document.createElement("li");
      // filename is a full path chosen by the browser; show only the last part.
      entry.textContent = `${item.filename.split(/[\/]/).pop()} — ${item.state}`;
      entry.title = item.filename;
      list.append(entry);
    }
  });
}

refresh();
